---

- name: install ntp
  apt: pkg=ntp state=present

- name: set ntp server
  lineinfile: dest=/etc/ntp.conf state=present regexp='^server ' line='server server1 iburst'

- name: start ntp
  service: name=ntp state=started enabled=true

