---

- name: install ntp
  apt: name=chrony state=present

- name: set ntp server
  lineinfile: dest=/etc/ntp.conf state=present regexp='^server ' line='server server1 iburst'

- name: start ntp
  service: name=chrony.service state=started enabled=yes

