---

- hosts: all
  become: true
  tasks:

  - name: Install updates (Ubuntu)
    apt:
      upgrade: dist
      update_cache: yes
    changed_when: false

- hosts: Controller
  become: true
  roles:
    - ntp
    - openstack
    - sql
    - mqueue
    - memcached
    - etcd
